{{/* Append the hardcoded volumes */}}
{{- define "vigil.hardcodedValues" -}}
persistence:
  config:
    enabled: true
    type: configMap
    name: {{ printf "%v-config" (include "common.names.fullname" .) }}
    subPath: config.cfg
    mountPath: /etc
    readOnly: true
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "vigil.hardcodedValues" . | fromYaml) -}}

{{ include "common.all" . }}
